name: ACTransmitter
version: ${project.version}
api-version: 1.13
main: com.nort721.transmitter.ACTransmitter
author: Nort721
description: An anticheat data transmision unit
depend: [ ProtocolLib ]